image: node:latest
include:
  - template: Dependency-Scanning.gitlab-ci.yml

cache:
  paths:
    - node_modules/

test:
  script:
    - npm i
    - npm test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

lint:
  script:
    - npm i
    - npm run lint
