image: node:latest

cache:
  paths:
    - node_modules/

test:
  script:
    - npm i
    - npm test
  coverage: 'Statements.*?(\d+(?:\.\d+)?)%'
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

lint:
  script:
    - npm i
    - npm run lint
