# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Reconfigure git to use HTTP authentication
      run: |
        git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, build, and run tests
      run: |
        npm ci
        npm run build --if-present
        npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: coverage/cobertura-coverage.xml

